package com.ocjadan.exhibitandroid.common.screensNavigator

import com.ocjadan.exhibitandroid.common.screensNavigator.INavControllerWrapper
import com.ocjadan.exhibitandroid.common.screensNavigator.NavControllerHelper

class NavControllerHelperMock(navControllerWrapper: INavControllerWrapper) : NavControllerHelper(navControllerWrapper)