package com.ocjadan.exhibitandroid.questions.questionsList

import com.ocjadan.exhibitandroid.questions.FetchQuestionsUseCase

class QuestionsListViewModelMock(fetchQuestionsUseCase: FetchQuestionsUseCase) : QuestionsListViewModel(fetchQuestionsUseCase)