package com.ocjadan.exhibitandroid.questions.questionsList

import com.ocjadan.exhibitandroid.questions.questionsList.items.FetchQuestionsListItemsUseCase

class QuestionsListViewModelMock(fetchQuestionsListItemsUseCase: FetchQuestionsListItemsUseCase) : QuestionsListViewModel(fetchQuestionsListItemsUseCase)