package com.ocjadan.exhibitandroid.questions.questionsList

class QuestionsListViewModelMock(fetchQuestionsListItemsUseCase: FetchQuestionsListItemsUseCase) : QuestionsListViewModel(fetchQuestionsListItemsUseCase)